version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    expose:
      - 9000
    networks:
      - laravel_network
      - db_network

  nginx:
    image: nginx:stable-alpine
    container_name: laravel_nginx
    restart: unless-stopped
   volumes:
  - ./docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - laravel_network
      - db_network
      - nginxpm   # connect to NPM network

networks:
  laravel_network:
    driver: bridge
  db_network:
    external: true
    name: db_network
  nginxpm:
    external: true # this is your Nginx Proxy Manager network
