version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_ENV: ${APP_ENV:-production}
      APP_DEBUG: ${APP_DEBUG:-false}
      APP_KEY: ${APP_KEY}
      DB_HOST: mysql        # make sure this matches your existing MySQL container name
      DB_PORT: 3306
      DB_DATABASE: mysql
      DB_USERNAME: laraveldb
      DB_PASSWORD: root
      
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
    networks:
      - nginxpm
    restart: unless-stopped
    external_links:
      - mysql

  web:
    image: nginx:alpine
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - nginxpm
    restart: unless-stopped
    # Nginx Proxy Manager will handle external access

networks:
  nginxpm:
    external: true
    name: nginxpm
